const { test, expect } = require("@playwright/test");

test("customer account requires legal consent and keeps a session", async ({ page }) => {
  await page.goto("/cuenta.html");
  await page.getByRole("tab", { name: "Crear cuenta", exact: true }).click();
  const registerForm = page.locator("#register-form");
  const email = `cliente-${Date.now()}@example.com`;
  await registerForm.locator('[name="name"]').fill("Cliente de prueba");
  await registerForm.locator('[name="email"]').fill(email);
  await registerForm.locator('[name="password"]').fill("UnaClaveSegura123");
  await page.getByRole("button", { name: "Crear cuenta", exact: true }).click();
  await expect(page.locator("#account-session")).toBeHidden();
  await page.locator('[name="acceptedTerms"]').check();
  await page.locator('[name="acceptedPrivacy"]').check();
  await page.getByRole("button", { name: "Crear cuenta", exact: true }).click();
  await expect(page.locator('[data-account-panel="verify-request"]')).toBeVisible();
  const messages = await (await page.request.get(`/__test/mail?email=${encodeURIComponent(email)}`)).json();
  const link = messages.at(-1).text.match(/http[^\s]+/)[0];
  await page.goto(link);
  await page.getByRole('button', { name: 'Confirmar mi correo', exact: true }).click();
  await page.locator('#login-form [name="identifier"]').fill(email);
  await page.locator('#login-form [name="password"]').fill('UnaClaveSegura123');
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(page.locator("#account-session")).toBeVisible();
  await page.reload();
  await expect(page.locator("#account-session")).toBeVisible();
  await page.getByRole("button", { name: "Cerrar sesión", exact: true }).click();
  await expect(page.locator("#account-panel")).toBeVisible();
  await page.locator("#login-form [name=\"identifier\"]").fill(email);
  await page.locator("#login-form [name=\"password\"]").fill("UnaClaveSegura123");
  await page.getByRole("button", { name: "Ingresar", exact: true }).click();
  await expect(page.locator("#account-session")).toBeVisible();
  await page.getByRole("button", { name: "Cerrar sesión", exact: true }).click();
  await expect(page.locator('#account-panel')).toBeVisible();
  await page.goto('/cuenta.html#forgot');
  await page.locator('#forgot-form [name=email]').fill(email);
  await page.locator('#forgot-form button[type=submit]').click();
  await expect(page.locator('#account-message')).toContainText('correo');
  const resetMessages = await (await page.request.get(`/__test/mail?email=${encodeURIComponent(email)}`)).json();
  await page.goto(resetMessages.at(-1).text.match(/http[^\s]+/)[0]);
  await page.locator('#reset-form [name=password]').fill('NuevaClaveSegura456');
  await page.locator('#reset-form [name=confirmation]').fill('NuevaClaveSegura456');
  await page.locator('#reset-form button[type=submit]').click();
  await expect(page.locator('#login-form')).toBeVisible();
  await page.locator('#login-form [name=identifier]').fill(email);
  await page.locator('#login-form [name=password]').fill('NuevaClaveSegura456');
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(page.locator('#account-session')).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await expect(page.locator('#account-panel')).toBeVisible();
  await page.locator("#login-form [name=\"identifier\"]").fill("admin");
  await page.locator("#login-form [name=\"password\"]").fill("Only-for-ui-tests-123");
  await page.getByRole("button", { name: "Ingresar", exact: true }).click();
  await expect(page).toHaveURL(/admin\.html/);
  await expect(page.locator("#admin-shell")).toBeVisible();
  expect((await (await page.request.get("/api/admin/session")).json()).authenticated).toBe(true);
  await page.goto("/cuenta.html");
  await expect(page).toHaveURL(/admin\.html/);
});

test('registration stays hidden when transactional email is unavailable', async ({ page }) => {
  await page.route('**/api/auth/config', route => route.fulfill({ json: { ok: true, emailEnabled: false } }));
  await page.goto('/cuenta.html#register');
  await expect(page.locator('#registration-note')).toBeVisible();
  await expect(page.locator('#register-form')).toBeHidden();
});
