const fs = require('node:fs');
const path = require('node:path');
const lucide = require('lucide');

const root = path.resolve(__dirname, '..');
const sourceDirectories = [path.join(root, 'views'), path.join(root, 'assets', 'scripts')];
const additionalIcons = [
  'badge-percent', 'camera', 'circle-check', 'flower-2', 'gift', 'grid-3x3',
  'layers-3', 'message-circle', 'sparkles', 'truck',
];

function sourceFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) return sourceFiles(file);
    return /\.(?:html|js)$/.test(entry.name) ? [file] : [];
  });
}

function buildIcons() {
  const names = new Set(additionalIcons);
  for (const directory of sourceDirectories) {
    for (const file of sourceFiles(directory)) {
      const source = fs.readFileSync(file, 'utf8');
      for (const match of source.matchAll(/data-lucide=["']([a-z][a-z0-9-]*)["']/g)) names.add(match[1]);
      for (const match of source.matchAll(/\bicon\(\s*["']([a-z][a-z0-9-]*)["']/g)) names.add(match[1]);
    }
  }
  const nodes = {};
  for (const name of [...names].sort()) {
    const pascal = name.split('-').map(part => part[0].toUpperCase() + part.slice(1)).join('');
    const node = lucide.icons[pascal];
    if (!Array.isArray(node)) throw new Error(`Icono Lucide no disponible: ${name}`);
    nodes[name] = node;
  }
  const runtime = `/* Lucide icon subset, ISC license in lucide-LICENSE. Generated by scripts/build-icons.js. */\n` +
`(()=>{'use strict';const nodes=${JSON.stringify(nodes)};const ns='http://www.w3.org/2000/svg';` +
`const defaults={xmlns:ns,width:'24',height:'24',viewBox:'0 0 24 24',fill:'none',stroke:'currentColor','stroke-width':'2','stroke-linecap':'round','stroke-linejoin':'round'};` +
`function createIcons({attrs={},root=document}={}){for(const element of root.querySelectorAll('[data-lucide]')){` +
`if(element.namespaceURI===ns)continue;const name=element.getAttribute('data-lucide');const icon=nodes[name];if(!icon)continue;` +
`const svg=document.createElementNS(ns,'svg');for(const [key,value] of Object.entries({...defaults,...attrs}))svg.setAttribute(key,String(value));` +
`for(const attr of element.attributes)svg.setAttribute(attr.name,attr.value);` +
`svg.setAttribute('class',['lucide','lucide-'+name,element.getAttribute('class')||'',attrs.class||''].filter(Boolean).join(' '));` +
`if(!svg.hasAttribute('aria-label')&&!svg.hasAttribute('aria-labelledby')&&!svg.hasAttribute('aria-hidden'))svg.setAttribute('aria-hidden','true');` +
`for(const [tag,properties] of icon){const child=document.createElementNS(ns,tag);for(const [key,value] of Object.entries(properties))child.setAttribute(key,String(value));svg.appendChild(child);}` +
`element.replaceWith(svg);}}window.lucide={createIcons};})();\n`;
  const destination = path.join(root, 'assets', 'vendor');
  fs.mkdirSync(destination, { recursive: true });
  fs.writeFileSync(path.join(destination, 'lucide.min.js'), runtime);
  fs.copyFileSync(path.join(path.dirname(require.resolve('lucide/package.json')), 'LICENSE'), path.join(destination, 'lucide-LICENSE'));
  console.log(`${names.size} iconos preparados (${Buffer.byteLength(runtime)} bytes).`);
}

if (require.main === module) buildIcons();
module.exports = { buildIcons };
